
# This workflow will build a steampipe plugi image and publish it to Google Container Registry
#
# To configure this workflow:
#
# 1. Set up secrets in your workspace:   STEAMPIPE_REGISTRY_SA_KEY with the Base64 encoded JSON service account key (https://github.com/GoogleCloudPlatform/github-actions/tree/docs/service-account-key/setup-gcloud#inputs).
#
# 3. Change the values for the IMAGE environment variables (below).
#
# For more support on how to run the workflow, please visit https://github.com/GoogleCloudPlatform/github-actions/tree/master/example-workflows/gke

name: Build and Deploy to GKE

on:
  workflow_dispatch
  #release:
  #  types: [created]

env:
  PROJECT_ID: steampipe
  IMAGE: static-site

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

#     # Setup gcloud CLI
#     - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
#       with:
#         service_account_key: ${{ secrets.STEAMPIPE_REGISTRY_SA_KEY }}
#         project_id: $PROJECT_ID

#     # Configure Docker to use the gcloud command-line tool as a credential
#     # helper for authentication
#     - run: |-
#         gcloud --quiet auth configure-docker

    # install oras
    - run: |-
        curl -LO https://github.com/deislabs/oras/releases/download/v0.8.1/oras_0.8.1_linux_amd64.tar.gz
        mkdir -p oras-install/
        tar -zxf oras_0.8.1_*.tar.gz -C oras-install/
        mv oras-install/oras /usr/local/bin/
        rm -rf oras_0.8.1_*.tar.gz oras-install/
      
    - run: oras version

#     # Build the Docker image
#     - name: Build
#       run: |-
#         docker build \
#           --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
#           --build-arg GITHUB_SHA="$GITHUB_SHA" \
#           --build-arg GITHUB_REF="$GITHUB_REF" \
#           .

#     # Push the Docker image to Google Container Registry
#     - name: Publish
#       run: |-
#         docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
